[build]
builder = "nixpacks"
buildCommand = "pip install poetry && poetry install"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[environments.production.variables]
PORT = "3000"
